# Importing important library

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import joblib

In [2]:
!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=17e7a2657d29271be5505a52ca58a846ca3bfb5cc784d8b0989abc76e6917c03
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [3]:
from word2number import w2n

In [4]:
!pip install matplotlib-venn

In [6]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [7]:
df.experience=df.experience.fillna("Zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

# Fillin the NAN values of Experience coloumn by number "0" by using word2num ibrary.
df.experience = df.experience.apply(w2n.word_to_num)<br>
df

In [9]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [10]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [11]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary($)']])


LinearRegression()

In [12]:
reg.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [13]:
reg.intercept_

array([14992.65144669])

In [14]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [15]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])

# Saving the ML model by using **Joblib Library** of Python in oreder to make it easy to be used by others just by sending the model_joblib file . We don't need to repeatedly tain the whole dataset for predicting the value of the salary

In [18]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [19]:
mj=joblib.load('model_joblib')

In [21]:
mj.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [22]:
mj.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

# Saving the ML model by using **Pickle Library** of Python in oreder to make it easy to be used by others just by sending the model_joblib file . We don't need to repeatedly tain the whole dataset for predicting the value of the salary

In [23]:
import pickle

In [25]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [27]:
with open('model_pickle','rb') as f:
  mp=pickle.load(f)

In [29]:
mp.predict([[2,4,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[42607.32127329]])