# Importing important library

In [17]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [25]:
!pip install word2number

In [35]:
from word2number import w2n

In [5]:
!pip install matplotlib-venn

In [8]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
df.experience=df.experience.fillna("Zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# Fillin the NAN values of Experience coloumn by number "0" by using word2num ibrary.
df.experience = df.experience.apply(w2n.word_to_num)<br>
df

In [37]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [39]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [40]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [41]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary($)']])


LinearRegression()

In [42]:
reg.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [43]:
reg.intercept_

array([14992.65144669])

In [44]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [45]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])